<?php

return [
    // Matching is case-insensitive and uses complete words/phrases, including punctuation.
    'aliases' => [
        'JavaScript' => ['javascript', 'java script'],
        'Node.js' => ['node.js', 'nodejs', 'node js'],
        'C#' => ['c#', 'c sharp'],
        'C++' => ['c++', 'cpp'],
        '.NET' => ['.net', 'dotnet'],
        'PostgreSQL' => ['postgresql', 'postgres'],
        'scikit-learn' => ['scikit-learn', 'scikit learn', 'sklearn'],
        'AWS' => ['aws', 'amazon web services'],
        'Google Cloud' => ['google cloud', 'google cloud platform', 'gcp'],
        'React Native' => ['react native', 'react-native'],
        'Vue' => ['vue', 'vue.js', 'vuejs'],
    ],
    // Each distinct phrase contributes once: title evidence = 3, document evidence = 1.
    'project_types' => [
        'Web-Based System' => ['web based', 'web application', 'web portal', 'website'],
        'Mobile Application' => ['mobile application', 'mobile app', 'android application', 'ios application'],
        'Desktop Application' => ['desktop application', 'desktop software'],
        'AI/ML System' => ['machine learning', 'artificial intelligence', 'deep learning'],
        'IoT System' => ['internet of things', 'iot', 'sensor network'],
        'Data Analytics / Decision Support System' => ['data analytics', 'decision support', 'predictive analytics'],
        'Information Management System' => ['information management', 'records management', 'inventory management'],
        'E-Commerce System' => ['e commerce', 'online shopping', 'online marketplace'],
        'Game Development' => ['game development', 'video game', 'educational game'],
        'Cybersecurity System' => ['cybersecurity', 'intrusion detection', 'network security'],
        'Computer Vision System' => ['computer vision', 'facial recognition', 'image classification', 'object detection'],
        'NLP System' => ['natural language processing', 'nlp', 'sentiment analysis', 'text classification'],
        'Cloud-Based System' => ['cloud based', 'cloud computing', 'cloud application'],
        'Networking System' => ['network monitoring', 'network management', 'routing protocol'],
        'Automation System' => ['automation', 'automated control'],
        'Recommendation System' => ['recommendation system', 'recommender system', 'adviser recommendation'],
        'GIS' => ['gis', 'geographic information system', 'geospatial'],
        'AR/VR' => ['augmented reality', 'virtual reality', 'mixed reality'],
    ],
    'expertise' => [
        'Web Development' => ['web development', 'web application', 'Laravel', 'PHP', 'HTML', 'CSS', 'JavaScript', 'Django', 'Flask', 'React', 'Vue', 'Angular', 'Node.js'],
        'Mobile Development' => ['mobile development', 'mobile application', 'Flutter', 'Android', 'Kotlin', 'React Native', 'Swift'],
        'Database Systems' => ['database management', 'database', 'MySQL', 'PostgreSQL', 'MongoDB', 'SQL', 'SQLite', 'Firebase'],
        'Networking' => ['Cisco', 'router', 'routing', 'switching', 'network', 'Packet Tracer', 'Wireshark'],
        'Cybersecurity' => ['cybersecurity', 'network security', 'intrusion detection', 'encryption', 'penetration testing'],
        'Machine Learning / Data Analytics' => ['machine learning', 'classification', 'regression', 'TensorFlow', 'PyTorch', 'scikit-learn', 'data analytics', 'predictive analytics'],
        'Software Engineering' => ['software engineering', 'software testing', 'software architecture'],
        'Systems Analysis' => ['systems analysis', 'requirements analysis', 'business process modeling'],
        'Cloud Computing' => ['AWS', 'Azure', 'Docker', 'cloud', 'Google Cloud'],
        'Internet of Things' => ['internet of things', 'iot', 'Arduino', 'Raspberry Pi', 'sensor network'],
        'Computer Vision' => ['computer vision', 'OpenCV', 'facial recognition', 'image classification', 'object detection'],
        'Natural Language Processing' => ['natural language processing', 'nlp', 'text classification', 'sentiment analysis'],
        'Game Development' => ['game development', 'video game', 'Unity'],
        'UI/UX' => ['ui/ux', 'user interface', 'user experience', 'usability testing'],
    ],
    'stop_words' => preg_split('/\s+/', 'a an the and or but for nor so yet of to in on at by with from as is are was were be been being this that these those it its we our you your they their he she his her i me us them can could would should will may might must shall do does did done have has had not no also into using used use based through between within each other than then there here such both all any some more most only about study research project development information application system systems proposed proposal result results paper chapter figure table section introduction methodology conclusion abstract summary implement implemented aims aim provides provide students student faculty university college'),
];
